theme: jekyll-theme-minimal
<a href="https://www.linkedin.com/in/aravinda-vijayaram-kumar-b9a9a4175/">👔 LinkedIn</a> instead of <a href="https://www.linkedin.com/in/aravinda-vijayaram-kumar-b9a9a4175/">View My LinkedIn Profile</a>

